# Generated by Django 3.1.1 on 2020-09-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='class_teacher',
            field=models.IntegerField(default=False, max_length=1),
        ),
    ]
