# Generated by Django 3.1.1 on 2020-09-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200916_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='class_teacher',
            field=models.CharField(default=False, max_length=1),
        ),
    ]
