# Generated by Django 3.1.1 on 2020-09-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200916_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_teacher',
            new_name='is_staff',
        ),
    ]
